<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use RuntimeException;

class PositionSeeder extends Seeder
{
    private const EVALUATION_GRADES = 360;

    /** @var list<string> */
    private const SEDES = [
        'DELTA', 'RIO', 'METROPOLITANA', 'MOREÑA', 'ECHEVESTE', 'MERCED',
        'SANTA RITA', '21 DE MARZO', 'BELLAVISTA', 'ESCOBEDO', 'HILAMAS',
    ];

    public function run(): void
    {
        DB::transaction(function (): void {
            $sedeIds = $this->resolveSedeIds();
            $rows = $this->rows();
            $positionIds = [];
            $supervisors = $this->supervisorMap($rows);

            foreach ($rows as $row) {
                [$sedeName, $departmentName, $positionName] = $row;
                $sedeId = $sedeIds[$sedeName];

                DB::table('departments')->updateOrInsert(
                    ['sede_id' => $sedeId, 'name' => $departmentName],
                    ['status' => true, 'updated_at' => now()],
                );

                $departmentId = (int) DB::table('departments')
                    ->where('sede_id', $sedeId)->where('name', $departmentName)->value('id');
                $order = $this->hierarchyOrder($positionName);

                DB::table('positions')->updateOrInsert(
                    ['department_id' => $departmentId, 'name' => $positionName],
                    [
                        'evaluation_grades' => self::EVALUATION_GRADES,
                        'description' => null,
                        'order' => $order,
                        'status' => true,
                        'updated_at' => now(),
                    ],
                );

                $key = $this->key($sedeName, $departmentName, $positionName);
                $positionIds[$key] = (int) DB::table('positions')
                    ->where('department_id', $departmentId)->where('name', $positionName)->value('id');
            }

            // Segunda pasada: resuelve el mapa explícito sin IDs fijos de departments/positions.
            foreach ($rows as [$sedeName, $departmentName, $positionName]) {
                $key = $this->key($sedeName, $departmentName, $positionName);
                $supervisorKey = $supervisors[$key] ?? null;
                $supervisorId = $supervisorKey === null ? null : ($positionIds[$supervisorKey] ?? null);

                if ($supervisorId === $positionIds[$key]) {
                    $supervisorId = null;
                }

                DB::table('positions')->where('id', $positionIds[$key])->update([
                    'supervisor_id' => $supervisorId,
                    'updated_at' => now(),
                ]);
            }
        });
    }

    /** @return array<string, int> */
    private function resolveSedeIds(): array
    {
        $ids = [];

        foreach (self::SEDES as $name) {
            $matches = DB::table('sedes')
                ->whereRaw('UPPER(TRIM(name)) = ?', [mb_strtoupper($name, 'UTF-8')])
                ->select('id')
                ->limit(2)
                ->get();

            if ($matches->isEmpty()) {
                throw new RuntimeException("No existe la sede requerida '{$name}'. Ejecuta primero SedeSeeder.");
            }

            if ($matches->count() > 1) {
                throw new RuntimeException("La sede '{$name}' está duplicada y no puede resolverse de forma inequívoca.");
            }

            $ids[$name] = (int) $matches->first()->id;
        }

        return $ids;
    }

    /** @return list<array{string,string,string}> */
    private function rows(): array
    {
        $tsv = <<<'TSV'
DELTA	SEGURO INTERNO	COORDINADOR DE SEGURO INTERNO
DELTA	SEGURO INTERNO	GESTOR DE SEGURO INTERNO
DELTA	SEGURO INTERNO	GERENTE DE SEGURO INTERNO OPT
DELTA	TI	ANALISTA DE SISTEMAS CONTPAQi
DELTA	TI	COORDINADOR DE TI
DELTA	TI	COORDINADOR DE GESTORIA DE ANALISIS
DELTA	TI	COORDINADOR DE DESARROLLO Y DATOS
DELTA	TI	AUXILIAR DE GESTORIA DE ANALISIS
DELTA	TI	DESARROLLADOR Jr.
DELTA	TI	ANALISTA TI
DELTA	TI	GERENTE DE TI DESARROLLO Y DATOS
DELTA	CONTRALORIA	COORD DE MTTO A LA TECNOLOGIA ABORDO
DELTA	CONTRALORIA	SUPERVISOR DE MTTO TECNOLOGIA ABORDO
DELTA	CONTRALORIA	TEC EN ELECTR DE MTTO A LA TECNO ABORDO
DELTA	CONTRALORIA	MONITORISTA DE CAR
DELTA	AUDITORIA INTERNA	COORDINADOR DE AUDITORIA INTERNA OPT
DELTA	AUDITORIA INTERNA	AUDITOR INTERNO OPT
DELTA	CAPITAL HUMANO	COORDINADOR DE RECLUTAMIENTO Y SELECCION
DELTA	CAPITAL HUMANO	INSTRUCTOR DE CAPACITACION OPT
DELTA	CAPITAL HUMANO	COORDINADOR DE CAPITAL HUMANO
DELTA	CAPITAL HUMANO	MEDICO DE SALUD INTEGRAL
DELTA	CAPITAL HUMANO	GERENTE DE CAPITAL HUMANO
DELTA	CAPITAL HUMANO	AUXILIAR DE INCIDENCIAS NOMINAS
DELTA	CAPITAL HUMANO	AUXILIAR DE RECLUTAMIENTO Y SELECECCION
DELTA	CAPITAL HUMANO	AUXILIAR RELACIONES LABORALES OPT
DELTA	CAPITAL HUMANO	SUPERVISOR DE CAPACITACION
DELTA	CAPITAL HUMANO	AUX DE COMUNICACIÓN ORGANIZACIONAL
DELTA	CAPITAL HUMANO	AUXILIAR DE CAPITAL HUMANO
DELTA	CAPITAL HUMANO	PELUQUERO
DELTA	DIESEL	AUXILIAR OPERATIVO DIESEL
DELTA	DIESEL	SUPERVISOR DE DIESEL OPERATIVO OPT
DELTA	DIESEL	AUXILIAR ADMVO DE DIESEL
DELTA	DIESEL	GERENTE DE DIESEL
DELTA	DIESEL	SUPERVISOR DE DIESEL ADMINISTRATIVO
DELTA	DIESEL	DESPACHADOR DE DIESEL
DELTA	DIESEL	SUPERVISOR DE CONTROL DE DIESEL MD OPT
DELTA	ADMINISTRATIVA	AUXILIAR ADMVO DE LIQ Y BOLETOS AXR
DELTA	ADMINISTRATIVA	COORDINADOR DE LIQUIDACION Y BOLETOS AXR
DELTA	ADMINISTRATIVA	CAJERO DE LIQUIDACION Y BOLETOS AXR
DELTA	MANTENIMIENTO	LAVADOR
DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE MTTO DE EDIFICIOS
DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	GERENTE DE MANTTO Y CONSER DE INMUEBLES
DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	CONTROL DE MONITOREO
DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS
DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	SUPERVISOR DE ACCESO
DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	INTENDENTE
DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR ADMINISTRATIVO
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	COORDINADOR DE ANALISIS
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	CONCENTRADOR
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	COORDINADOR DE PLNCION Y OPRCION DE SER
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	ANALISTA
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	SERVICIOS
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	GERENTE DE PLNCION Y OPE DE SERV OPT
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	AUX ADMVO DE PLNCION Y OPRCION DE SER
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	MONITORISTA CMR
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	CONTROLADOR
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	AUXILIAR DE ANALISIS
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	INSPECTOR OPERATIVO ABORDO
DELTA	PRODUCTIVIDAD AXR	GERENTE DE PRODTVD
DELTA	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR DELTA
DELTA	PRODUCTIVIDAD AXR	COORDINADOR DE PRODTVD
DELTA	PRODUCTIVIDAD AXR	AUXILIAR OPERATIVO DE PRODTVD AXR
DELTA	PRODUCTIVIDAD AXR	OPERADOR AXR AUSL DELTA
DELTA	PRODUCTIVIDAD AXR	OPERADOR AXR RSIT DELTA
DELTA	PRODUCTIVIDAD AXR	OPERADOR DE AXR AUSL 06 DELTA
RIO	ALMACEN Y ABASTECIMIENTO	GERENTE DE ALMACEN Y ABASTECIMIENTO
RIO	ALMACEN Y ABASTECIMIENTO	COORDINADOR DE ALMACEN Y ABASTECIMIENTO
RIO	ALMACEN Y ABASTECIMIENTO	AUXILIAR DE ALMACEN Y ABASTECIMIENTO
RIO	ALMACEN Y ABASTECIMIENTO	AUXILIAR ADMVO DE ALMACEN
RIO	MANTENIMIENTO	GERENTE GRAL MANTENIMIENTO
RIO	MANTENIMIENTO	COORDINADOR DE MANTTO
RIO	MANTENIMIENTO	SUPERVISOR DE SEGURIDAD VEHICULAR OPT
RIO	MANTENIMIENTO	TECNICO LIDER MECANICO RIO OPT
RIO	MANTENIMIENTO	TECNICO LIDER MECANICO
RIO	MANTENIMIENTO	TECNICO LIDER ELECTRICO
RIO	MANTENIMIENTO	TECNICO LIDER CARROCERO
RIO	MANTENIMIENTO	SUPERVISOR DE CONTROL DE LLANTAS
RIO	MANTENIMIENTO	ASISTENTE DE GERENCIA GRAL MTTO
RIO	MANTENIMIENTO	AUXILIAR ADMVO MTTO
RIO	MANTENIMIENTO	OPERADOR GRUA OPT
RIO	MANTENIMIENTO	JEFE DE PATIO OPT
RIO	MANTENIMIENTO	MECANICO A
RIO	MANTENIMIENTO	MECANICO B
RIO	MANTENIMIENTO	MECANICO B OPT
RIO	MANTENIMIENTO	MECANICO C
RIO	MANTENIMIENTO	CARROCERO A
RIO	MANTENIMIENTO	CARROCERO A OPT
RIO	MANTENIMIENTO	CARROCERO B
RIO	MANTENIMIENTO	CARROCERO C
RIO	MANTENIMIENTO	ELECTRICO B
RIO	MANTENIMIENTO	ELECTRICO C
RIO	MANTENIMIENTO	LAVADOR
RIO	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS
RIO	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	INTENDENTE
RIO	ADMINISTRATIVA	GERENTE ADMINISTRATIVO
RIO	ADMINISTRATIVA	AUXILIAR DE ADMINISTRACION B
RIO	ADMINISTRATIVA	AUXILIAR DE ADMINISTRACION C
RIO	ADMINISTRATIVA	GESTOR ADMINISTRATIVO
RIO	ADMINISTRATIVA	COORDINADOR DE ADMINISTRACION
RIO	CONTRALORIA	GERENTE DE CONTRALORIA
RIO	CONTRALORIA	SUPERVISOR DE PUNTOS DE VENTA
RIO	CONTRALORIA	AUXILIAR ADMVO DE CONTRALORIA
RIO	CONTRALORIA	COORDINADOR DE CONTRALORIA
RIO	CONTRALORIA	MONITORISTA DE CAR
RIO	DIRECCION GRAL	DIRECTOR DE UNIDADES DE NEGOCIO OPT
RIO	DIRECCION GRAL	ASISTENTE ADMVO DE UNID DE NEGOCIO OPT
RIO	DIRECCION GRAL	DIRECTORA ADMINISTRATIVA
RIO	DIRECCION GRAL	CONSEJERO DELEGADO OPT
RIO	DIRECCION GRAL	ASISTENTE ADMVO DE DIRECCION ADMVA
RIO	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD SIT RIO
RIO	PRODUCTIVIDAD AXR	OPERADOR SIT TRONCAL RIO OPT1
RIO	PRODUCTIVIDAD AXR	OPERADOR SIT PRETRO RIO OPT1
RIO	PRODUCTIVIDAD AXR	OPERADOR SIT EXPRES RIO OPT1
METROPOLITANA	PRODUCTIVIDAD SUB E INTER	SUPERVISOR DE PRODTVD SUB E INTER ASP
METROPOLITANA	PRODUCTIVIDAD SUB E INTER	SUPERVISOR DE PRODTVD SUB E INTER ACG
METROPOLITANA	PRODUCTIVIDAD SUB E INTER	AUXILIAR ADMVO PRODTVD SUB E INTER A
METROPOLITANA	PRODUCTIVIDAD SUB E INTER	AUXILIAR ADMVO PRODTVD SUB E INTER B
METROPOLITANA	PRODUCTIVIDAD SUB E INTER	OPERADOR SUB E INTER ACG
METROPOLITANA	PRODUCTIVIDAD SUB E INTER	OPERADOR SUB E INTER ASP
METROPOLITANA	PRODUCTIVIDAD SUB E INTER	OPERADOR SUB E INTER AUSL
METROPOLITANA	PRODUCTIVIDAD AXR	OPERADOR AXR LCE METRO
METROPOLITANA	PRODUCTIVIDAD AXR	OPERADOR AXR AUSL METRO
METROPOLITANA	PLANEACION Y OPERACIÓN DE SERVICIOS	SERVICIOS FORANEOS
METROPOLITANA	PLANEACION Y OPERACIÓN DE SERVICIOS	CONTROLADOR
METROPOLITANA	MANTENIMIENTO	LAVADOR
METROPOLITANA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS
METROPOLITANA	ADMINISTRATIVA	COORDINADOR DE LIQ Y BOLETOS SUB E INTER
METROPOLITANA	ADMINISTRATIVA	CAJERO DE LIQUIDACION Y BOLETOS AXR
METROPOLITANA	ADMINISTRATIVA	CAJERO DE LIQ Y BOLETOS SUB E INTER
METROPOLITANA	ADMINISTRATIVA	AUXILIAR ADMVO DE LIQ Y BOL SUB E INTER
METROPOLITANA	CONTRALORIA	PROMOTOR DE VENTA DE LIQ Y BOLETOS
METROPOLITANA	TI	AUXILIAR DE GESTORIA DE ANALISIS
MOREÑA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	INTENDENTE
MOREÑA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS
MOREÑA	MANTENIMIENTO	LAVADOR
MOREÑA	ADMINISTRATIVA	CAJERO DE LIQUIDACION Y BOLETOS AXR
MOREÑA	PLANEACION Y OPERACIÓN DE SERVICIOS	CONTROLADOR
MOREÑA	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR MOREÑA
MOREÑA	PRODUCTIVIDAD AXR	OPERADOR AXR LCE MOREÑA
MOREÑA	PRODUCTIVIDAD AXR	OPERADOR AXR AUSL MOREÑA
ECHEVESTE	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS
ECHEVESTE	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	INTENDENTE
ECHEVESTE	MANTENIMIENTO	LAVADOR
ECHEVESTE	MANTENIMIENTO	MECANICO A
ECHEVESTE	ADMINISTRATIVA	CAJERO DE LIQUIDACION Y BOLETOS AXR
ECHEVESTE	DIESEL	DESPACHADOR DE DIESEL
ECHEVESTE	PLANEACION Y OPERACIÓN DE SERVICIOS	CONTROLADOR
ECHEVESTE	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR ECHEVESTE
ECHEVESTE	PRODUCTIVIDAD AXR	OPERADOR AXR LCE ECHEVESTE
ECHEVESTE	PRODUCTIVIDAD AXR	OPERADOR SIT PRETRO ECHEVESTE OPT1
ECHEVESTE	PRODUCTIVIDAD AXR	OPERADOR AXR AUSL ECHEVESTE
ECHEVESTE	PRODUCTIVIDAD AXR	OPERADOR DE AXR AUSL 06 ECHEVESTE
ECHEVESTE	PRODUCTIVIDAD AXR	OPERADOR AXR LCB ECHEVESTE
MERCED	DIESEL	DESPACHADOR DE DIESEL
MERCED	DIESEL	SUPERVISOR DE CONTROL DE DIESEL MD
MERCED	MANTENIMIENTO	MECANICO B
MERCED	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS
MERCED	PLANEACION Y OPERACIÓN DE SERVICIOS	CONTROLADOR
MERCED	PRODUCTIVIDAD AXR	OPERADOR AXR LCB MERCED
MERCED	PRODUCTIVIDAD AXR	OPERADOR AXR LCE MERCED
MERCED	PRODUCTIVIDAD AXR	OPERADOR AXR AUSL MERCED
21 DE MARZO	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	INTENDENTE
21 DE MARZO	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS
21 DE MARZO	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS OPT
21 DE MARZO	PLANEACION Y OPERACIÓN DE SERVICIOS	CONTROLADOR
21 DE MARZO	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR 21 DE MARZO
21 DE MARZO	PRODUCTIVIDAD AXR	OPERADOR AXR LCB 21 DE MARZO
21 DE MARZO	PRODUCTIVIDAD AXR	OPERADOR AXR LCE 21 DE MARZO
21 DE MARZO	PRODUCTIVIDAD AXR	OPERADOR AXR AUSL 21 DE MARZO
BELLAVISTA	ALMACEN Y ABASTECIMIENTO	SUBCOORD DE ALMACEN Y ABASTECIMIENTO
BELLAVISTA	ALMACEN Y ABASTECIMIENTO	AUXILIAR DE ALMACEN Y ABASTECIMIENTO
BELLAVISTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS
BELLAVISTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	INTENDENTE
BELLAVISTA	MANTENIMIENTO	SUPERVISOR DE MTTO
BELLAVISTA	MANTENIMIENTO	COORDINADOR DE MTTO BELLAVISTA OPT
BELLAVISTA	MANTENIMIENTO	TECNICO LIDER CARROCERO
BELLAVISTA	MANTENIMIENTO	TECNICO LIDER MECANICO BELLAVISTA OPT
BELLAVISTA	MANTENIMIENTO	TECNICO LIDER MUELLERO
BELLAVISTA	MANTENIMIENTO	AUX ADMVO MTTO
BELLAVISTA	MANTENIMIENTO	MUELLERO A
BELLAVISTA	MANTENIMIENTO	MECANICO A
BELLAVISTA	MANTENIMIENTO	MECANICO B
BELLAVISTA	MANTENIMIENTO	MECANICO C
BELLAVISTA	MANTENIMIENTO	CARROCERO A
BELLAVISTA	MANTENIMIENTO	CARROCERO B
BELLAVISTA	MANTENIMIENTO	ELECTRICO C
BELLAVISTA	MANTENIMIENTO	LAVADOR
BELLAVISTA	MANTENIMIENTO	LAVADOR OPT
BELLAVISTA	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR BELLAVISTA
BELLAVISTA	PRODUCTIVIDAD AXR	OPERADOR AXR LCB BELLAVISTA
BELLAVISTA	PRODUCTIVIDAD AXR	OPERADOR AXR LCE BELLAVISTA
BELLAVISTA	PRODUCTIVIDAD AXR	OPERADOR AXR AUSL BELLAVISTA
ESCOBEDO	MANTENIMIENTO	LAVADOR
ESCOBEDO	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS
ESCOBEDO	PLANEACION Y OPERACIÓN DE SERVICIOS	CONTROLADOR
ESCOBEDO	PRODUCTIVIDAD AXR	OPERADOR AXR LCB ESCOBEDO
ESCOBEDO	PRODUCTIVIDAD AXR	OPERADOR AXR LCE ESCOBEDO
HILAMAS	ADMINISTRATIVA	CAJERO DE LIQUIDACION Y BOLETOS AXR
HILAMAS	DIESEL	SUPERVISOR DE CONTROL DE DIESEL MD
HILAMAS	DIESEL	DESPACHADOR DE DIESEL
HILAMAS	MANTENIMIENTO	LAVADOR
HILAMAS	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS
HILAMAS	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	INTENDENTE
HILAMAS	PLANEACION Y OPERACIÓN DE SERVICIOS	CONTROLADOR
HILAMAS	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR HILAMAS
HILAMAS	PRODUCTIVIDAD AXR	OPERADOR AXR LCE HILAMAS
HILAMAS	PRODUCTIVIDAD AXR	OPERADOR DE AXR LCE 06 HILAMAS
TSV;

        $unique = [];
        foreach (preg_split('/\R/', trim($tsv)) as $line) {
            $row = array_map('trim', explode("\t", $line));
            if (count($row) !== 3) {
                throw new RuntimeException("Fila TSV inválida: {$line}");
            }
            $unique[implode("\x1F", $row)] = $row;
        }

        return array_values($unique);
    }

    private function hierarchyOrder(string $name): int
    {
        $upper = mb_strtoupper($name);
        return match (true) {
            str_contains($upper, 'CONSEJERO') => 5,
            str_contains($upper, 'DIRECTOR') || str_contains($upper, 'DIRECTORA') => 10,
            str_contains($upper, 'GERENTE') => 20,
            str_contains($upper, 'COORDINADOR') || str_contains($upper, 'COORD ') => 30,
            str_contains($upper, 'SUBCOORD') => 35,
            str_contains($upper, 'SUPERVISOR') || str_contains($upper, 'JEFE') => 40,
            str_contains($upper, 'TECNICO LIDER') => 50,
            str_contains($upper, 'ASISTENTE') || str_contains($upper, 'ANALISTA') || str_contains($upper, 'AUDITOR') || str_contains($upper, 'MEDICO') || str_contains($upper, 'INSTRUCTOR') => 60,
            str_contains($upper, 'AUXILIAR') || str_contains($upper, 'AUX ') => 70,
            default => 80,
        };
    }

    /**
     * Mapa canónico conciliado mediante análisis multiformato de "050626 ORGANIGRAMA P"
     * (VSDX, PNG, JSON, PDF y HTML). Sólo se aplican relaciones directa/equivalencia
     * incluidas en propuesta_relaciones_canonicas.tsv; las restantes quedan en null.
     * Toda posición no listada queda deliberadamente en null.
     *
     * @param list<array{string,string,string}> $rows
     * @return array<string, string|null>
     */
    private function supervisorMap(array $rows): array
    {
        $map = [];
        foreach ($rows as [$sede, $department, $position]) {
            $map[$this->key($sede, $department, $position)] = null;
        }

        $tsv = <<<'TSV'
21 DE MARZO	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	SUPERVISOR DE ACCESO	equivalencia
21 DE MARZO	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS OPT	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	SUPERVISOR DE ACCESO	equivalencia
21 DE MARZO	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	INTENDENTE	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	GERENTE DE MANTTO Y CONSER DE INMUEBLES	equivalencia
21 DE MARZO	PRODUCTIVIDAD AXR	OPERADOR AXR AUSL 21 DE MARZO	21 DE MARZO	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR 21 DE MARZO	equivalencia
21 DE MARZO	PRODUCTIVIDAD AXR	OPERADOR AXR LCB 21 DE MARZO	21 DE MARZO	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR 21 DE MARZO	equivalencia
21 DE MARZO	PRODUCTIVIDAD AXR	OPERADOR AXR LCE 21 DE MARZO	21 DE MARZO	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR 21 DE MARZO	equivalencia
21 DE MARZO	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR 21 DE MARZO	DELTA	PRODUCTIVIDAD AXR	GERENTE DE PRODTVD	equivalencia
BELLAVISTA	ALMACEN Y ABASTECIMIENTO	AUXILIAR DE ALMACEN Y ABASTECIMIENTO	BELLAVISTA	ALMACEN Y ABASTECIMIENTO	SUBCOORD DE ALMACEN Y ABASTECIMIENTO	directa
BELLAVISTA	MANTENIMIENTO	AUX ADMVO MTTO	BELLAVISTA	MANTENIMIENTO	SUPERVISOR DE MTTO	directa
BELLAVISTA	MANTENIMIENTO	CARROCERO A	BELLAVISTA	MANTENIMIENTO	TECNICO LIDER CARROCERO	directa
BELLAVISTA	MANTENIMIENTO	CARROCERO B	BELLAVISTA	MANTENIMIENTO	TECNICO LIDER CARROCERO	directa
BELLAVISTA	MANTENIMIENTO	LAVADOR	RIO	MANTENIMIENTO	GERENTE GRAL MANTENIMIENTO	equivalencia
BELLAVISTA	MANTENIMIENTO	LAVADOR OPT	RIO	MANTENIMIENTO	GERENTE GRAL MANTENIMIENTO	equivalencia
BELLAVISTA	MANTENIMIENTO	MECANICO A	BELLAVISTA	MANTENIMIENTO	TECNICO LIDER MECANICO BELLAVISTA OPT	directa
BELLAVISTA	MANTENIMIENTO	MECANICO B	BELLAVISTA	MANTENIMIENTO	TECNICO LIDER MECANICO BELLAVISTA OPT	directa
BELLAVISTA	MANTENIMIENTO	MECANICO C	BELLAVISTA	MANTENIMIENTO	TECNICO LIDER MECANICO BELLAVISTA OPT	directa
BELLAVISTA	MANTENIMIENTO	MUELLERO A	BELLAVISTA	MANTENIMIENTO	TECNICO LIDER MUELLERO	directa
BELLAVISTA	MANTENIMIENTO	SUPERVISOR DE MTTO	BELLAVISTA	MANTENIMIENTO	COORDINADOR DE MTTO BELLAVISTA OPT	directa
BELLAVISTA	MANTENIMIENTO	TECNICO LIDER CARROCERO	BELLAVISTA	MANTENIMIENTO	SUPERVISOR DE MTTO	directa
BELLAVISTA	MANTENIMIENTO	TECNICO LIDER MECANICO BELLAVISTA OPT	BELLAVISTA	MANTENIMIENTO	SUPERVISOR DE MTTO	equivalencia
BELLAVISTA	MANTENIMIENTO	TECNICO LIDER MUELLERO	BELLAVISTA	MANTENIMIENTO	SUPERVISOR DE MTTO	directa
BELLAVISTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	SUPERVISOR DE ACCESO	equivalencia
BELLAVISTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	INTENDENTE	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	GERENTE DE MANTTO Y CONSER DE INMUEBLES	equivalencia
BELLAVISTA	PRODUCTIVIDAD AXR	OPERADOR AXR AUSL BELLAVISTA	BELLAVISTA	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR BELLAVISTA	equivalencia
BELLAVISTA	PRODUCTIVIDAD AXR	OPERADOR AXR LCB BELLAVISTA	BELLAVISTA	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR BELLAVISTA	equivalencia
BELLAVISTA	PRODUCTIVIDAD AXR	OPERADOR AXR LCE BELLAVISTA	BELLAVISTA	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR BELLAVISTA	equivalencia
BELLAVISTA	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR BELLAVISTA	DELTA	PRODUCTIVIDAD AXR	GERENTE DE PRODTVD	equivalencia
DELTA	ADMINISTRATIVA	AUXILIAR ADMVO DE LIQ Y BOLETOS AXR	DELTA	ADMINISTRATIVA	COORDINADOR DE LIQUIDACION Y BOLETOS AXR	directa
DELTA	ADMINISTRATIVA	CAJERO DE LIQUIDACION Y BOLETOS AXR	DELTA	ADMINISTRATIVA	COORDINADOR DE LIQUIDACION Y BOLETOS AXR	directa
DELTA	ADMINISTRATIVA	COORDINADOR DE LIQUIDACION Y BOLETOS AXR	RIO	ADMINISTRATIVA	GERENTE ADMINISTRATIVO	directa
DELTA	AUDITORIA INTERNA	AUDITOR INTERNO OPT	DELTA	AUDITORIA INTERNA	COORDINADOR DE AUDITORIA INTERNA OPT	equivalencia
DELTA	CAPITAL HUMANO	AUX DE COMUNICACIÓN ORGANIZACIONAL	DELTA	CAPITAL HUMANO	GERENTE DE CAPITAL HUMANO	directa
DELTA	CAPITAL HUMANO	AUXILIAR DE CAPITAL HUMANO	DELTA	CAPITAL HUMANO	COORDINADOR DE CAPITAL HUMANO	directa
DELTA	CAPITAL HUMANO	AUXILIAR DE INCIDENCIAS NOMINAS	DELTA	CAPITAL HUMANO	COORDINADOR DE CAPITAL HUMANO	directa
DELTA	CAPITAL HUMANO	AUXILIAR DE RECLUTAMIENTO Y SELECECCION	DELTA	CAPITAL HUMANO	COORDINADOR DE RECLUTAMIENTO Y SELECCION	directa
DELTA	CAPITAL HUMANO	AUXILIAR RELACIONES LABORALES OPT	DELTA	CAPITAL HUMANO	COORDINADOR DE CAPITAL HUMANO	equivalencia
DELTA	CAPITAL HUMANO	COORDINADOR DE CAPITAL HUMANO	DELTA	CAPITAL HUMANO	GERENTE DE CAPITAL HUMANO	directa
DELTA	CAPITAL HUMANO	COORDINADOR DE RECLUTAMIENTO Y SELECCION	DELTA	CAPITAL HUMANO	GERENTE DE CAPITAL HUMANO	directa
DELTA	CAPITAL HUMANO	INSTRUCTOR DE CAPACITACION OPT	DELTA	CAPITAL HUMANO	SUPERVISOR DE CAPACITACION	equivalencia
DELTA	CAPITAL HUMANO	MEDICO DE SALUD INTEGRAL	DELTA	CAPITAL HUMANO	GERENTE DE CAPITAL HUMANO	directa
DELTA	CAPITAL HUMANO	PELUQUERO	DELTA	CAPITAL HUMANO	GERENTE DE CAPITAL HUMANO	directa
DELTA	CAPITAL HUMANO	SUPERVISOR DE CAPACITACION	DELTA	CAPITAL HUMANO	GERENTE DE CAPITAL HUMANO	directa
DELTA	CONTRALORIA	COORD DE MTTO A LA TECNOLOGIA ABORDO	RIO	CONTRALORIA	GERENTE DE CONTRALORIA	directa
DELTA	CONTRALORIA	MONITORISTA DE CAR	DELTA	CONTRALORIA	SUPERVISOR DE MTTO TECNOLOGIA ABORDO	directa
DELTA	CONTRALORIA	SUPERVISOR DE MTTO TECNOLOGIA ABORDO	DELTA	CONTRALORIA	COORD DE MTTO A LA TECNOLOGIA ABORDO	directa
DELTA	CONTRALORIA	TEC EN ELECTR DE MTTO A LA TECNO ABORDO	DELTA	CONTRALORIA	SUPERVISOR DE MTTO TECNOLOGIA ABORDO	directa
DELTA	DIESEL	AUXILIAR ADMVO DE DIESEL	DELTA	DIESEL	SUPERVISOR DE DIESEL ADMINISTRATIVO	directa
DELTA	DIESEL	AUXILIAR OPERATIVO DIESEL	DELTA	DIESEL	SUPERVISOR DE DIESEL OPERATIVO OPT	directa
DELTA	DIESEL	DESPACHADOR DE DIESEL	DELTA	DIESEL	SUPERVISOR DE DIESEL OPERATIVO OPT	directa
DELTA	DIESEL	SUPERVISOR DE CONTROL DE DIESEL MD OPT	DELTA	DIESEL	GERENTE DE DIESEL	equivalencia
DELTA	DIESEL	SUPERVISOR DE DIESEL ADMINISTRATIVO	DELTA	DIESEL	GERENTE DE DIESEL	directa
DELTA	DIESEL	SUPERVISOR DE DIESEL OPERATIVO OPT	DELTA	DIESEL	GERENTE DE DIESEL	equivalencia
DELTA	MANTENIMIENTO	LAVADOR	RIO	MANTENIMIENTO	GERENTE GRAL MANTENIMIENTO	equivalencia
DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR ADMINISTRATIVO	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	GERENTE DE MANTTO Y CONSER DE INMUEBLES	directa
DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	SUPERVISOR DE ACCESO	directa
DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE MTTO DE EDIFICIOS	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	GERENTE DE MANTTO Y CONSER DE INMUEBLES	directa
DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	CONTROL DE MONITOREO	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	SUPERVISOR DE ACCESO	directa
DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	INTENDENTE	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	GERENTE DE MANTTO Y CONSER DE INMUEBLES	directa
DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	SUPERVISOR DE ACCESO	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	GERENTE DE MANTTO Y CONSER DE INMUEBLES	directa
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	ANALISTA	DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	COORDINADOR DE ANALISIS	directa
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	AUX ADMVO DE PLNCION Y OPRCION DE SER	DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	COORDINADOR DE ANALISIS	directa
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	AUXILIAR DE ANALISIS	DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	COORDINADOR DE ANALISIS	directa
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	CONCENTRADOR	DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	COORDINADOR DE ANALISIS	directa
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	COORDINADOR DE ANALISIS	DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	GERENTE DE PLNCION Y OPE DE SERV OPT	directa
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	COORDINADOR DE PLNCION Y OPRCION DE SER	DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	GERENTE DE PLNCION Y OPE DE SERV OPT	directa
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	INSPECTOR OPERATIVO ABORDO	DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	COORDINADOR DE PLNCION Y OPRCION DE SER	directa
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	MONITORISTA CMR	DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	COORDINADOR DE PLNCION Y OPRCION DE SER	directa
DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	SERVICIOS	DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	COORDINADOR DE ANALISIS	directa
DELTA	PRODUCTIVIDAD AXR	AUXILIAR OPERATIVO DE PRODTVD AXR	DELTA	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR DELTA	directa
DELTA	PRODUCTIVIDAD AXR	COORDINADOR DE PRODTVD	DELTA	PRODUCTIVIDAD AXR	GERENTE DE PRODTVD	equivalencia
DELTA	PRODUCTIVIDAD AXR	OPERADOR AXR AUSL DELTA	DELTA	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR DELTA	equivalencia
DELTA	PRODUCTIVIDAD AXR	OPERADOR AXR RSIT DELTA	DELTA	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR DELTA	equivalencia
DELTA	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR DELTA	DELTA	PRODUCTIVIDAD AXR	GERENTE DE PRODTVD	equivalencia
DELTA	SEGURO INTERNO	COORDINADOR DE SEGURO INTERNO	DELTA	SEGURO INTERNO	GERENTE DE SEGURO INTERNO OPT	directa
DELTA	SEGURO INTERNO	GESTOR DE SEGURO INTERNO	DELTA	SEGURO INTERNO	COORDINADOR DE SEGURO INTERNO	directa
DELTA	TI	ANALISTA DE SISTEMAS CONTPAQi	DELTA	TI	GERENTE DE TI DESARROLLO Y DATOS	equivalencia
DELTA	TI	ANALISTA TI	DELTA	TI	COORDINADOR DE TI	directa
DELTA	TI	AUXILIAR DE GESTORIA DE ANALISIS	DELTA	TI	COORDINADOR DE GESTORIA DE ANALISIS	directa
DELTA	TI	COORDINADOR DE DESARROLLO Y DATOS	DELTA	TI	GERENTE DE TI DESARROLLO Y DATOS	directa
DELTA	TI	COORDINADOR DE GESTORIA DE ANALISIS	DELTA	TI	GERENTE DE TI DESARROLLO Y DATOS	directa
DELTA	TI	COORDINADOR DE TI	DELTA	TI	GERENTE DE TI DESARROLLO Y DATOS	directa
DELTA	TI	DESARROLLADOR Jr.	DELTA	TI	COORDINADOR DE DESARROLLO Y DATOS	equivalencia
ECHEVESTE	MANTENIMIENTO	LAVADOR	RIO	MANTENIMIENTO	GERENTE GRAL MANTENIMIENTO	equivalencia
ECHEVESTE	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	SUPERVISOR DE ACCESO	equivalencia
ECHEVESTE	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	INTENDENTE	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	GERENTE DE MANTTO Y CONSER DE INMUEBLES	equivalencia
ECHEVESTE	PRODUCTIVIDAD AXR	OPERADOR AXR AUSL ECHEVESTE	ECHEVESTE	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR ECHEVESTE	equivalencia
ECHEVESTE	PRODUCTIVIDAD AXR	OPERADOR AXR LCE ECHEVESTE	ECHEVESTE	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR ECHEVESTE	equivalencia
ECHEVESTE	PRODUCTIVIDAD AXR	OPERADOR DE AXR AUSL 06 ECHEVESTE	ECHEVESTE	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR ECHEVESTE	equivalencia
ECHEVESTE	PRODUCTIVIDAD AXR	OPERADOR SIT PRETRO ECHEVESTE OPT1	RIO	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD SIT RIO	equivalencia
ECHEVESTE	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR ECHEVESTE	DELTA	PRODUCTIVIDAD AXR	GERENTE DE PRODTVD	equivalencia
ESCOBEDO	MANTENIMIENTO	LAVADOR	RIO	MANTENIMIENTO	GERENTE GRAL MANTENIMIENTO	equivalencia
ESCOBEDO	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	SUPERVISOR DE ACCESO	equivalencia
HILAMAS	DIESEL	DESPACHADOR DE DIESEL	HILAMAS	DIESEL	SUPERVISOR DE CONTROL DE DIESEL MD	directa
HILAMAS	DIESEL	SUPERVISOR DE CONTROL DE DIESEL MD	DELTA	DIESEL	GERENTE DE DIESEL	directa
HILAMAS	MANTENIMIENTO	LAVADOR	RIO	MANTENIMIENTO	GERENTE GRAL MANTENIMIENTO	equivalencia
HILAMAS	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	SUPERVISOR DE ACCESO	equivalencia
HILAMAS	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	INTENDENTE	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	GERENTE DE MANTTO Y CONSER DE INMUEBLES	equivalencia
HILAMAS	PRODUCTIVIDAD AXR	OPERADOR AXR LCE HILAMAS	HILAMAS	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR HILAMAS	equivalencia
HILAMAS	PRODUCTIVIDAD AXR	OPERADOR DE AXR LCE 06 HILAMAS	HILAMAS	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR HILAMAS	equivalencia
HILAMAS	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR HILAMAS	DELTA	PRODUCTIVIDAD AXR	GERENTE DE PRODTVD	equivalencia
MERCED	DIESEL	DESPACHADOR DE DIESEL	MERCED	DIESEL	SUPERVISOR DE CONTROL DE DIESEL MD	directa
MERCED	DIESEL	SUPERVISOR DE CONTROL DE DIESEL MD	DELTA	DIESEL	GERENTE DE DIESEL	directa
MERCED	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	SUPERVISOR DE ACCESO	equivalencia
METROPOLITANA	ADMINISTRATIVA	AUXILIAR ADMVO DE LIQ Y BOL SUB E INTER	METROPOLITANA	ADMINISTRATIVA	COORDINADOR DE LIQ Y BOLETOS SUB E INTER	directa
METROPOLITANA	ADMINISTRATIVA	CAJERO DE LIQ Y BOLETOS SUB E INTER	METROPOLITANA	ADMINISTRATIVA	COORDINADOR DE LIQ Y BOLETOS SUB E INTER	directa
METROPOLITANA	ADMINISTRATIVA	COORDINADOR DE LIQ Y BOLETOS SUB E INTER	RIO	ADMINISTRATIVA	GERENTE ADMINISTRATIVO	directa
METROPOLITANA	CONTRALORIA	PROMOTOR DE VENTA DE LIQ Y BOLETOS	RIO	CONTRALORIA	SUPERVISOR DE PUNTOS DE VENTA	directa
METROPOLITANA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	SUPERVISOR DE ACCESO	equivalencia
METROPOLITANA	PLANEACION Y OPERACIÓN DE SERVICIOS	SERVICIOS FORANEOS	DELTA	PLANEACION Y OPERACIÓN DE SERVICIOS	COORDINADOR DE PLNCION Y OPRCION DE SER	directa
METROPOLITANA	PRODUCTIVIDAD SUB E INTER	AUXILIAR ADMVO PRODTVD SUB E INTER A	DELTA	PRODUCTIVIDAD AXR	GERENTE DE PRODTVD	equivalencia
METROPOLITANA	PRODUCTIVIDAD SUB E INTER	AUXILIAR ADMVO PRODTVD SUB E INTER B	DELTA	PRODUCTIVIDAD AXR	GERENTE DE PRODTVD	equivalencia
METROPOLITANA	PRODUCTIVIDAD SUB E INTER	OPERADOR SUB E INTER ACG	METROPOLITANA	PRODUCTIVIDAD SUB E INTER	SUPERVISOR DE PRODTVD SUB E INTER ACG	equivalencia
METROPOLITANA	PRODUCTIVIDAD SUB E INTER	OPERADOR SUB E INTER ASP	METROPOLITANA	PRODUCTIVIDAD SUB E INTER	SUPERVISOR DE PRODTVD SUB E INTER ASP	equivalencia
METROPOLITANA	PRODUCTIVIDAD SUB E INTER	OPERADOR SUB E INTER AUSL	METROPOLITANA	PRODUCTIVIDAD SUB E INTER	SUPERVISOR DE PRODTVD SUB E INTER ASP	equivalencia
METROPOLITANA	PRODUCTIVIDAD SUB E INTER	SUPERVISOR DE PRODTVD SUB E INTER ACG	DELTA	PRODUCTIVIDAD AXR	GERENTE DE PRODTVD	equivalencia
METROPOLITANA	PRODUCTIVIDAD SUB E INTER	SUPERVISOR DE PRODTVD SUB E INTER ASP	DELTA	PRODUCTIVIDAD AXR	GERENTE DE PRODTVD	equivalencia
METROPOLITANA	TI	AUXILIAR DE GESTORIA DE ANALISIS	DELTA	TI	COORDINADOR DE GESTORIA DE ANALISIS	directa
MOREÑA	MANTENIMIENTO	LAVADOR	RIO	MANTENIMIENTO	GERENTE GRAL MANTENIMIENTO	equivalencia
MOREÑA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	SUPERVISOR DE ACCESO	equivalencia
MOREÑA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	INTENDENTE	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	GERENTE DE MANTTO Y CONSER DE INMUEBLES	equivalencia
MOREÑA	PRODUCTIVIDAD AXR	OPERADOR AXR AUSL MOREÑA	MOREÑA	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR MOREÑA	equivalencia
MOREÑA	PRODUCTIVIDAD AXR	OPERADOR AXR LCE MOREÑA	MOREÑA	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR MOREÑA	equivalencia
MOREÑA	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD AXR MOREÑA	DELTA	PRODUCTIVIDAD AXR	GERENTE DE PRODTVD	equivalencia
RIO	ADMINISTRATIVA	AUXILIAR DE ADMINISTRACION B	RIO	ADMINISTRATIVA	COORDINADOR DE ADMINISTRACION	equivalencia
RIO	ADMINISTRATIVA	AUXILIAR DE ADMINISTRACION C	RIO	ADMINISTRATIVA	COORDINADOR DE ADMINISTRACION	equivalencia
RIO	ADMINISTRATIVA	COORDINADOR DE ADMINISTRACION	RIO	ADMINISTRATIVA	GERENTE ADMINISTRATIVO	directa
RIO	ADMINISTRATIVA	GESTOR ADMINISTRATIVO	RIO	ADMINISTRATIVA	COORDINADOR DE ADMINISTRACION	directa
RIO	ALMACEN Y ABASTECIMIENTO	AUXILIAR ADMVO DE ALMACEN	RIO	ALMACEN Y ABASTECIMIENTO	COORDINADOR DE ALMACEN Y ABASTECIMIENTO	directa
RIO	ALMACEN Y ABASTECIMIENTO	AUXILIAR DE ALMACEN Y ABASTECIMIENTO	RIO	ALMACEN Y ABASTECIMIENTO	COORDINADOR DE ALMACEN Y ABASTECIMIENTO	directa
RIO	ALMACEN Y ABASTECIMIENTO	COORDINADOR DE ALMACEN Y ABASTECIMIENTO	RIO	ALMACEN Y ABASTECIMIENTO	GERENTE DE ALMACEN Y ABASTECIMIENTO	directa
RIO	CONTRALORIA	AUXILIAR ADMVO DE CONTRALORIA	RIO	CONTRALORIA	SUPERVISOR DE PUNTOS DE VENTA	directa
RIO	CONTRALORIA	COORDINADOR DE CONTRALORIA	RIO	CONTRALORIA	GERENTE DE CONTRALORIA	directa
RIO	CONTRALORIA	MONITORISTA DE CAR	DELTA	CONTRALORIA	SUPERVISOR DE MTTO TECNOLOGIA ABORDO	directa
RIO	CONTRALORIA	SUPERVISOR DE PUNTOS DE VENTA	RIO	CONTRALORIA	COORDINADOR DE CONTRALORIA	directa
RIO	DIRECCION GRAL	ASISTENTE ADMVO DE DIRECCION ADMVA	RIO	DIRECCION GRAL	DIRECTORA ADMINISTRATIVA	directa
RIO	DIRECCION GRAL	ASISTENTE ADMVO DE UNID DE NEGOCIO OPT	RIO	DIRECCION GRAL	DIRECTOR DE UNIDADES DE NEGOCIO OPT	equivalencia
RIO	DIRECCION GRAL	DIRECTOR DE UNIDADES DE NEGOCIO OPT	RIO	DIRECCION GRAL	CONSEJERO DELEGADO OPT	equivalencia
RIO	DIRECCION GRAL	DIRECTORA ADMINISTRATIVA	RIO	DIRECCION GRAL	CONSEJERO DELEGADO OPT	directa
RIO	MANTENIMIENTO	ASISTENTE DE GERENCIA GRAL MTTO	RIO	MANTENIMIENTO	GERENTE GRAL MANTENIMIENTO	directa
RIO	MANTENIMIENTO	AUXILIAR ADMVO MTTO	RIO	MANTENIMIENTO	COORDINADOR DE MANTTO	directa
RIO	MANTENIMIENTO	CARROCERO A	RIO	MANTENIMIENTO	TECNICO LIDER CARROCERO	directa
RIO	MANTENIMIENTO	CARROCERO A OPT	RIO	MANTENIMIENTO	TECNICO LIDER CARROCERO	equivalencia
RIO	MANTENIMIENTO	CARROCERO B	RIO	MANTENIMIENTO	TECNICO LIDER CARROCERO	directa
RIO	MANTENIMIENTO	CARROCERO C	RIO	MANTENIMIENTO	TECNICO LIDER CARROCERO	directa
RIO	MANTENIMIENTO	COORDINADOR DE MANTTO	RIO	MANTENIMIENTO	GERENTE GRAL MANTENIMIENTO	directa
RIO	MANTENIMIENTO	ELECTRICO B	RIO	MANTENIMIENTO	TECNICO LIDER ELECTRICO	directa
RIO	MANTENIMIENTO	ELECTRICO C	RIO	MANTENIMIENTO	TECNICO LIDER ELECTRICO	directa
RIO	MANTENIMIENTO	JEFE DE PATIO OPT	RIO	MANTENIMIENTO	COORDINADOR DE MANTTO	equivalencia
RIO	MANTENIMIENTO	LAVADOR	RIO	MANTENIMIENTO	GERENTE GRAL MANTENIMIENTO	equivalencia
RIO	MANTENIMIENTO	MECANICO A	RIO	MANTENIMIENTO	TECNICO LIDER MECANICO	directa
RIO	MANTENIMIENTO	MECANICO B	RIO	MANTENIMIENTO	TECNICO LIDER MECANICO	directa
RIO	MANTENIMIENTO	MECANICO B OPT	RIO	MANTENIMIENTO	TECNICO LIDER MECANICO	equivalencia
RIO	MANTENIMIENTO	MECANICO C	RIO	MANTENIMIENTO	TECNICO LIDER MECANICO	directa
RIO	MANTENIMIENTO	OPERADOR GRUA OPT	RIO	MANTENIMIENTO	COORDINADOR DE MANTTO	equivalencia
RIO	MANTENIMIENTO	SUPERVISOR DE CONTROL DE LLANTAS	RIO	MANTENIMIENTO	GERENTE GRAL MANTENIMIENTO	directa
RIO	MANTENIMIENTO	SUPERVISOR DE SEGURIDAD VEHICULAR OPT	RIO	MANTENIMIENTO	GERENTE GRAL MANTENIMIENTO	equivalencia
RIO	MANTENIMIENTO	TECNICO LIDER CARROCERO	RIO	MANTENIMIENTO	COORDINADOR DE MANTTO	directa
RIO	MANTENIMIENTO	TECNICO LIDER ELECTRICO	RIO	MANTENIMIENTO	COORDINADOR DE MANTTO	directa
RIO	MANTENIMIENTO	TECNICO LIDER MECANICO	RIO	MANTENIMIENTO	COORDINADOR DE MANTTO	directa
RIO	MANTENIMIENTO	TECNICO LIDER MECANICO RIO OPT	RIO	MANTENIMIENTO	COORDINADOR DE MANTTO	equivalencia
RIO	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	AUXILIAR DE CONTROL DE ACCESOS	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	SUPERVISOR DE ACCESO	equivalencia
RIO	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	INTENDENTE	DELTA	MANTENIMIENTO Y CONSERVACION DE INMUEBLES	GERENTE DE MANTTO Y CONSER DE INMUEBLES	equivalencia
RIO	PRODUCTIVIDAD AXR	OPERADOR SIT EXPRES RIO OPT1	RIO	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD SIT RIO	equivalencia
RIO	PRODUCTIVIDAD AXR	OPERADOR SIT PRETRO RIO OPT1	RIO	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD SIT RIO	equivalencia
RIO	PRODUCTIVIDAD AXR	OPERADOR SIT TRONCAL RIO OPT1	RIO	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD SIT RIO	equivalencia
RIO	PRODUCTIVIDAD AXR	SUPERVISOR DE PRODTVD SIT RIO	DELTA	PRODUCTIVIDAD AXR	GERENTE DE PRODTVD	equivalencia
TSV;

        foreach (preg_split('/\R/', trim($tsv)) as $line) {
            $parts = array_map('trim', explode("\t", $line));
            if (count($parts) !== 7) {
                throw new RuntimeException("Relación jerárquica TSV inválida: {$line}");
            }

            [$sede, $department, $position, $supervisorSede, $supervisorDepartment, $supervisorPosition, $evidence] = $parts;
            if (! in_array($evidence, ['directa', 'equivalencia'], true)) {
                throw new RuntimeException("Nivel de evidencia no permitido: {$line}");
            }

            $childKey = $this->key($sede, $department, $position);
            $supervisorKey = $this->key($supervisorSede, $supervisorDepartment, $supervisorPosition);

            if (! array_key_exists($childKey, $map) || ! array_key_exists($supervisorKey, $map)) {
                throw new RuntimeException("La relación jerárquica referencia un puesto inexistente: {$line}");
            }

            if ($childKey === $supervisorKey) {
                throw new RuntimeException("La relación jerárquica se autorreferencia: {$line}");
            }

            if (! $this->hasExplicitAuthority($supervisorPosition)) {
                throw new RuntimeException("El supervisor no tiene autoridad explícita: {$line}");
            }

            $map[$childKey] = $supervisorKey;
        }

        $this->assertAcyclic($map);

        return $map;
    }

    private function hasExplicitAuthority(string $position): bool
    {
        $upper = mb_strtoupper($position);

        foreach (['CONSEJERO', 'DIRECTOR', 'DIRECTORA', 'GERENTE', 'COORDINADOR', 'COORD ', 'SUBCOORD', 'SUPERVISOR', 'JEFE', 'TECNICO LIDER'] as $authority) {
            if (str_contains($upper, $authority)) {
                return true;
            }
        }

        return false;
    }

    /** @param array<string, string|null> $map */
    private function assertAcyclic(array $map): void
    {
        foreach (array_keys($map) as $origin) {
            $visited = [];
            $current = $origin;

            while (($map[$current] ?? null) !== null) {
                if (isset($visited[$current])) {
                    throw new RuntimeException("El mapa jerárquico contiene un ciclo desde: {$origin}");
                }

                $visited[$current] = true;
                $current = $map[$current];
            }
        }
    }

    private function key(string $sede, string $department, string $position): string
    {
        return implode("\x1F", [$sede, $department, $position]);
    }
}
